apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-nodejs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/lanru2001/eks-nodejs-react-application.git"
    targetRevision: HEAD
    path: kubernetes
  destination:
    namespace: default
    server: "https://kubernetes.default.svc" 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
     selfHeal: true
     prune: true
