# A VirtualService defines a set of traffic routing rules to apply when a host is addressed. Each routing rule defines matching criteria for traffic of a specific protocol. If the traffic is matched, then it is sent to a named destination service (or subset/version of it) defined in the registry
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: user-nodejs-app-virtualservice
  namespace: default
spec:
  gateways:
  - user-nodejs-app-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: <servicename>.default.svc.cluster.local
        port:
          number: 80
